services:
  cryptobot:
    build: .
    container_name: cryptobot
    restart: always
    command: ["python", "-u", "main.py"]
    volumes:
      - ./config.yaml:/app/config.yaml:ro
      - ./data:/app/data
      - ./logs:/app/logs

  cryptobot-ai:
    build: .
    container_name: cryptobot-ai
    restart: always
    command: ["python", "-u", "main_ai.py"]
    volumes:
      - ./config_ai.yaml:/app/config_ai.yaml:ro
      - ./data_ai:/app/data
      - ./logs_ai:/app/logs
